<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-20T14:03:26Z" name="Default suite" finished-at="2024-11-20T14:03:45Z" duration-ms="18892">
    <groups>
    </groups>
    <test started-at="2024-11-20T14:03:26Z" name="Default test" finished-at="2024-11-20T14:03:45Z" duration-ms="18892">
      <class name="org.test.Sampletest2">
        <test-method is-config="true" signature="beforeclass()[pri:0, instance:org.test.Sampletest2@2eea88a1]" started-at="2024-11-20T14:03:26Z" name="beforeclass" finished-at="2024-11-20T14:03:29Z" duration-ms="2535" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeclass -->
        <test-method is-config="true" signature="beforemethod()[pri:0, instance:org.test.Sampletest2@2eea88a1]" started-at="2024-11-20T14:03:29Z" name="beforemethod" finished-at="2024-11-20T14:03:29Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method signature="testb()[pri:0, instance:org.test.Sampletest2@2eea88a1]" started-at="2024-11-20T14:03:29Z" name="testb" finished-at="2024-11-20T14:03:36Z" duration-ms="7189" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
testtttt expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
testtttt expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at org.test.Sampletest2.testb(Sampletest2.java:59)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testb -->
        <test-method is-config="true" signature="aftermethod()[pri:0, instance:org.test.Sampletest2@2eea88a1]" started-at="2024-11-20T14:03:36Z" name="aftermethod" finished-at="2024-11-20T14:03:36Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method is-config="true" signature="beforemethod()[pri:0, instance:org.test.Sampletest2@2eea88a1]" started-at="2024-11-20T14:03:36Z" name="beforemethod" finished-at="2024-11-20T14:03:36Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method signature="testbb()[pri:0, instance:org.test.Sampletest2@2eea88a1]" started-at="2024-11-20T14:03:36Z" name="testbb" finished-at="2024-11-20T14:03:45Z" duration-ms="9134" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testbb -->
        <test-method is-config="true" signature="aftermethod()[pri:0, instance:org.test.Sampletest2@2eea88a1]" started-at="2024-11-20T14:03:45Z" name="aftermethod" finished-at="2024-11-20T14:03:45Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method is-config="true" signature="afterclass()[pri:0, instance:org.test.Sampletest2@2eea88a1]" started-at="2024-11-20T14:03:45Z" name="afterclass" finished-at="2024-11-20T14:03:45Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterclass -->
      </class> <!-- org.test.Sampletest2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
